FROM public.ecr.aws/amazonlinux/amazonlinux:2023-minimal

ARG BINARY
COPY ${BINARY} /opt/application/server
RUN chmod 0555 /opt/application/server

USER 65534:65534
EXPOSE 8080
ENTRYPOINT ["/opt/application/server"]
