resource "aws_s3_bucket" "assets" { bucket = "wsc2026-cdn-asset-${lower(var.candidate_id)}" }
resource "aws_s3_bucket_public_access_block" "assets" { bucket = aws_s3_bucket.assets.id
block_public_acls = true
block_public_policy = true
ignore_public_acls = true
restrict_public_buckets = true }
resource "aws_s3_bucket_versioning" "assets" { bucket = aws_s3_bucket.assets.id
versioning_configuration { status = "Enabled" } }
resource "aws_s3_object" "origin" { bucket = aws_s3_bucket.assets.id
key = "origin/${basename(var.origin_image)}"
source = var.origin_image
etag = filemd5(var.origin_image) }
resource "aws_cloudfront_origin_access_control" "assets" { name = "wsc2026-cdn-oac"
description = "wsc2026 assets"
origin_access_control_origin_type = "s3"
signing_behavior = "always"
signing_protocol = "sigv4" }

resource "aws_cloudfront_cache_policy" "main" { name = "wsc2026-cache-policy"
default_ttl = 86400
max_ttl = 31536000
min_ttl = 0
parameters_in_cache_key_and_forwarded_to_origin { enable_accept_encoding_brotli = true
enable_accept_encoding_gzip = true
cookies_config { cookie_behavior = "none" }
headers_config { header_behavior = "none" }
query_strings_config { query_string_behavior = "all" } } }
resource "aws_cloudfront_origin_request_policy" "main" { name = "wsc2026-origin-policy"
cookies_config { cookie_behavior = "none" }
headers_config { header_behavior = "whitelist"
headers { items = ["CloudFront-Is-Mobile-Viewer", "CloudFront-Is-Desktop-Viewer"] } }
query_strings_config { query_string_behavior = "all" } }
resource "aws_cloudfront_function" "device" { name = "wsc2026-device-detect"
runtime = "cloudfront-js-2.0"
publish = true
code = file("${path.module}/assets/device.js") }
resource "aws_cloudfront_function" "response" { name = "wsc2026-response-header"
runtime = "cloudfront-js-2.0"
publish = true
code = file("${path.module}/assets/response.js") }

data "aws_iam_policy_document" "edge_assume" { statement { actions = ["sts:AssumeRole"]
principals { type = "Service"
identifiers = ["lambda.amazonaws.com", "edgelambda.amazonaws.com"] } } }
resource "aws_iam_role" "edge" { name = "wsc2026-resize-role"
assume_role_policy = data.aws_iam_policy_document.edge_assume.json }
resource "aws_iam_policy" "edge" { name = "wsc2026-resize-policy"
policy = jsonencode({ Version = "2012-10-17", Statement = [{ Effect = "Allow", Action = ["s3:GetObject", "s3:PutObject"], Resource = "${aws_s3_bucket.assets.arn}/*" }, { Effect = "Allow", Action = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"], Resource = "arn:aws:logs:*:${data.aws_caller_identity.current.account_id}:*" }] }) }
resource "aws_iam_role_policy_attachment" "edge" { role = aws_iam_role.edge.name
policy_arn = aws_iam_policy.edge.arn }
data "archive_file" "edge" { type = "zip"
source_file = "${path.module}/assets/resize.py"
output_path = "${path.module}/resize.zip" }
resource "aws_lambda_function" "edge" { function_name = "wsc2026-resize"
role = aws_iam_role.edge.arn
runtime = "python3.12"
handler = "resize.handler"
filename = data.archive_file.edge.output_path
source_code_hash = data.archive_file.edge.output_base64sha256
publish = true
timeout = 30
memory_size = 1024
layers = [var.pillow_layer_arn] }

resource "aws_cloudfront_distribution" "main" {
  enabled = true
is_ipv6_enabled = true
price_class = "PriceClass_All"
default_root_object = aws_s3_object.origin.key
  origin { domain_name = aws_s3_bucket.assets.bucket_regional_domain_name
origin_id = "assets"
origin_access_control_id = aws_cloudfront_origin_access_control.assets.id }
  default_cache_behavior {
    target_origin_id = "assets"
viewer_protocol_policy = "redirect-to-https"
allowed_methods = ["GET", "HEAD", "OPTIONS"]
cached_methods = ["GET", "HEAD"]
compress = true
    cache_policy_id = aws_cloudfront_cache_policy.main.id
origin_request_policy_id = aws_cloudfront_origin_request_policy.main.id
    function_association { event_type = "viewer-request"
function_arn = aws_cloudfront_function.device.arn }
    function_association { event_type = "viewer-response"
function_arn = aws_cloudfront_function.response.arn }
    lambda_function_association { event_type = "origin-response"
lambda_arn = aws_lambda_function.edge.qualified_arn }
  }
  restrictions { geo_restriction { restriction_type = "none" } }
  viewer_certificate { cloudfront_default_certificate = true }
  tags = { Name = "wsc2026-cdn" }
  depends_on = [aws_iam_role_policy_attachment.edge]
}
data "aws_iam_policy_document" "bucket" { statement { actions = ["s3:GetObject"]
resources = ["${aws_s3_bucket.assets.arn}/*"]
principals { type = "Service"
identifiers = ["cloudfront.amazonaws.com"] }
condition { test = "StringEquals"
variable = "AWS:SourceArn"
values = [aws_cloudfront_distribution.main.arn] } }
statement { actions = ["s3:PutObject"]
resources = ["${aws_s3_bucket.assets.arn}/resized/*"]
principals { type = "AWS"
identifiers = [aws_iam_role.edge.arn] } } }
resource "aws_s3_bucket_policy" "assets" { bucket = aws_s3_bucket.assets.id
policy = data.aws_iam_policy_document.bucket.json }
output "cloudfront_domain" { value = aws_cloudfront_distribution.main.domain_name }
