output "cloudfront_url" { value = "https://${aws_cloudfront_distribution.web.domain_name}" }
output "alb_url" { value = "http://${aws_lb.book.dns_name}" }
output "eks_cluster_name" { value = aws_eks_cluster.main.name }
output "ecr_repository_url" { value = aws_ecr_repository.book.repository_url }
output "cluster_endpoint" { value = aws_eks_cluster.main.endpoint
sensitive = true }
output "cluster_ca" { value = aws_eks_cluster.main.certificate_authority[0].data
sensitive = true }
output "dynamodb_table_name" { value = aws_dynamodb_table.book.name }
