config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        Parser cri
        Tag kube.*
        Mem_Buf_Limit 20MB
        Skip_Long_Lines On
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log On
    [FILTER]
        Name grep
        Match kube.*
        Exclude $kubernetes['namespace_name'] ^wsc2026-logging$
  outputs: |
    [OUTPUT]
        Name opentelemetry
        Match kube.*
        Host wsc2026-otel-collector-opentelemetry-collector
        Port 4318
        Logs_uri /v1/logs
        Tls Off
